apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dev
commonLabels:
  env: dev
images:
  - name: myhk2009/nodetest
    newName: myhk2009/nodetest
    newTag: 20221226-dev-89f2974041
bases:
  - ../../base
patchesStrategicMerge:
  - service-lb.yaml
