apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodejs
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      serviceAccountName: node-deployment-sa
      containers:
      - image: myhk2009/nodetest:latest
        name: nodejs
        env:
          - name: APP_ENV
            valueFrom:
              secretKeyRef:
                name: aws-secret
                key: appenv
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  labels:
    app: lb-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: nodejs